{{- if .Values.selfMonitor.podMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vmagent
spec:
  selector:
    matchLabels:
      {{- include "prometheus-benchmark.labels" $ | nindent 6 }}
      job: vmagent
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vmalert
spec:
  selector:
    matchLabels:
      {{- include "prometheus-benchmark.labels" $ | nindent 6 }}
      job: vmalert
  podMetricsEndpoints:
  - port: metrics
{{- end -}}
