{{- if .Values.selfMonitor.podMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vmagent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prom-bench
      job: vmagent
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vmalert
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prom-bench
      job: vmalert
  podMetricsEndpoints:
  - port: metrics
{{- end -}}
