{
 "title": "Benchmark prom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Query duration 50th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile)(prometheus_engine_query_duration_seconds{quantile=~\"0.5\", job=\"prom-benchmark\",slice!=\"result_sort\"}) ",
     "legendFormat": "prom-{{quantile}}"
    },
    {
     "expr": "max(vm_request_duration_seconds{quantile=~\"0.5\"}) by (path, quantile,instance) > 0",
     "legendFormat": "vm-{{quantile}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Query duration 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile)(prometheus_engine_query_duration_seconds{quantile=~\"0.99\", job=\"prom-benchmark\",slice!=\"result_sort\"}) ",
     "legendFormat": "prom-{{quantile}}"
    },
    {
     "expr": "max(vm_request_duration_seconds{quantile=~\"0.99\"}) by (path, quantile) > 0",
     "legendFormat": "vm-{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory(All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\".*-vmcluster\"})",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prom-benchmark\"}",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "CPU Usage(All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\".*-vmcluster\"}[$__rate_interval]))",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"prom-benchmark\"}[$__rate_interval]))",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "ThroughPut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*bench.*\"}[$__rate_interval]))",
     "legendFormat": "Reads-prom"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*bench.*\"}[$__rate_interval]))",
     "legendFormat": "Writes-prom"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*vmstorage.*\"}[$__rate_interval]))",
     "legendFormat": "writes-vm"
    },
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*vmstorage.*\"}[$__rate_interval]))",
     "legendFormat": "reads-vm"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{namespace=\"observability\", type=\"storage/hour_metric_ids\"}) / 2",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "prometheus_tsdb_head_series{job=\"prom-benchmark\"}",
     "legendFormat": "prom"
    }
   ]
  }
 ]
}