{
 "title": "Benchmark prom vmsingle",
 "time": { "from": "2023-03-04T17:08:49.683Z", "to": "2023-03-05T00:30:44.065Z" },
 "templating": {
  "list": [
   {
    "name": "vm_job",
    "query": {
     "query": "label_values(vm_app_uptime_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Churn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=~\"$vm_job\"}[$__rate_interval]))"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_created_total{namespace=\"observability\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{namespace=\"observability\",job=\"$vm_job\"}[$__rate_interval])) > 0",
     "legendFormat": "ingest"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{namespace=\"observability\",job=\"$vm_job\",type=\"storage/hour_metric_ids\"})",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "prometheus_tsdb_head_series{job=\"prom-benchmark\"}",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "Query duration 50th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile)(prometheus_engine_query_duration_seconds{quantile=~\"0.5\", job=\"prom-benchmark\",slice!=\"result_sort\"}) ",
     "legendFormat": "prom-{{quantile}}"
    },
    {
     "expr": "max(vm_request_duration_seconds{job=~\"$vm_job\",quantile=~\"0.5\"}) by (quantile,instance) > 0",
     "legendFormat": "vm-{{quantile}}"
    }
   ]
  },
  {
   "title": "Query duration 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile)(prometheus_engine_query_duration_seconds{quantile=~\"0.99\", job=\"prom-benchmark\",slice!=\"result_sort\"}) ",
     "legendFormat": "prom-{{quantile}}"
    },
    {
     "expr": "max(vm_request_duration_seconds{job=\"$vm_job\",quantile=~\"0.99\"}) by (quantile) > 0",
     "legendFormat": "vm-{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory(All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$vm_job\"})",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prom-benchmark\"}",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "CPU Usage(All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$vm_job\"}[$__rate_interval]))",
     "legendFormat": "vmcluster"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"prom-benchmark\"}[$__rate_interval]))",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "Bytes Per Data Point",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{namespace=\"observability\"}[2h])\n/ \n  rate(prometheus_tsdb_compaction_chunk_samples_sum{namespace=\"observability\"}[2h])",
     "legendFormat": "prom"
    },
    {
     "expr": "sum(vm_data_size_bytes{job=~\"$vm_job\"}) / sum(vm_rows{job=~\"$vm_job\"})",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"observability\",persistentvolumeclaim=\"vmsingle-vmsingle-benchmark\"}",
     "legendFormat": "vm"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"observability\",persistentvolumeclaim=\"prometheus-prom-benchmark-db-prometheus-prom-benchmark-0\"}",
     "legendFormat": "prom"
    }
   ]
  },
  {
   "title": "IO ThroughPut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\"prometheus-prom.*\"}[$__rate_interval]))",
     "legendFormat": "Writes-prom"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\"vmsingle.*\"}[$__rate_interval]))",
     "legendFormat": "writes-vm"
    }
   ]
  }
 ]
}