{
 "title": "bench vm",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "churn rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Churn rate",
   "type": "graph",
   "description": "Shows the rate and total number of new series created over last 24h.\n\nHigh churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nThe higher churn rate is, the more resources required to handle it. Consider to keep the churn rate as low as possible.\n\nTo investigate stats about most expensive series use `api/v1/status/tsdb` handler. More details here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://valyala.medium.com/high-cardinality-tsdb-benchmarks-victoriametrics-vs-timescaledb-vs-influxdb-13e6ee64dd6b",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{namespace=\"observability\"}[$__rate_interval]))",
     "legendFormat": "churn rate"
    },
    {
     "expr": "sum(increase(vm_new_timeseries_created_total{namespace=\"observability\"}[24h]))",
     "legendFormat": "new series over 24h"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{namespace=\"observability\"}[$__rate_interval])) > 0",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Slow inserts",
   "type": "graph",
   "description": "The percentage of slow inserts comparing to total insertion rate during the last 5 minutes. \n\nThe less value is better. If percentage remains high (>10%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of active time series. \n\nIn general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on may other factors such as the number of labels per time series and the length of label values.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_slow_row_inserts_total{namespace=\"observability\"}[$__rate_interval])) / sum(rate(vm_rows_inserted_total{namespace=\"observability\"}[$__rate_interval]))",
     "legendFormat": "slow inserts"
    }
   ]
  },
  {
   "title": "Slow queries rate",
   "type": "graph",
   "description": "Slow queries according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_slow_queries_total{namespace=\"observability\"}[$__rate_interval]))",
     "legendFormat": "slow queries rate"
    }
   ]
  },
  {
   "title": "VMAgent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Persistent queue size  ($instance) to ($url)",
   "type": "timeseries",
   "description": "Shows the persistent queue size of pending samples in bytes >2MB which hasn't been flushed to remote storage yet. \n\nIncreasing of value might be a sign of connectivity issues. In such cases, vmagent starts to flush pending data on disk with attempt to send it later once connection is restored.\n\nRemote write URLs are hidden by default but might be unveiled once `-remoteWrite.showURL` is set to true.\n\nClick on the line and choose Drilldown to show CPU usage per instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_pending_data_bytes{namespace=\"benchmark-prom\"}) by (job, url) > 2e6",
     "legendFormat": "{{job}} => {{url}}"
    }
   ]
  },
  {
   "title": "Persistent queue dropped rate",
   "type": "timeseries",
   "description": "Shows rate of dropped samples from persistent queue. VMagent drops samples from queue if in-memory and on-disk queues are full and it is unable to flush them to remote storage.\nThe max size of on-disk queue is configured by `-remoteWrite.maxDiskUsagePerURL` flag.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(vm_persistentqueue_bytes_dropped_total{namespace=\"benchmark-prom\"}[$__rate_interval])) by (path) > 0",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "benchmark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{namespace=\"observability\"}[$__rate_interval])) > 0",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "graph",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_entries{namespace=\"observability\", type=\"storage/hour_metric_ids\"}) / 2",
     "legendFormat": "Active time series"
    }
   ]
  },
  {
   "title": "Read Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{namespace=\"observability\", path=~\".*/api/v1/(query|query_range)\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(vm_http_request_errors_total{namespace=\"observability\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Query latency",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{namespace=\"observability\", quantile=~\"(0.5|0.99)\",path=\"/api/v1/query\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Memory Usage (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (max by(pod) (container_memory_working_set_bytes{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(min by(pod)(container_spec_memory_limit_bytes{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"} > 0))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum (max by(pod) (container_memory_working_set_bytes{namespace=\"observability\",pod=~\"vmstorage-vmcluster.*\", container!=\"\"}))",
     "legendFormat": "vmstorage-total"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}) / sum by(pod) (kube_pod_container_resource_limits{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\",resource=\"memory\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage(All)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"observability\",pod=~\"vmstorage-vmcluster.*\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "vmstorage-total"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}[$__rate_interval])) / (min by(pod) (container_spec_cpu_quota{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"} / container_spec_cpu_period{namespace=\"observability\",pod=~\".*vmcluster.*\", container!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk writes/reads (All)",
   "type": "graph",
   "description": "Shows the number of bytes read/write from the storage layer.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*vmcluster.*\"}[$__rate_interval])))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+|/dev/sd.+|/dev/nvme.+\", container!=\"\",  namespace=\"observability\", pod=~\".*vmcluster.*\"}[$__rate_interval])))",
     "legendFormat": "write"
    }
   ]
  }
 ]
}